using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace partial_class
{
    // File: Thermostat.Designer.cs
    public partial class Thermostat
    {
        private double _currentTemperature;
        private bool _isActive;

        // Imagine this is generated by a UI designer or a database mapper
        public void InitializeHardware()
        {
            _isActive = true;
            _currentTemperature = 22.0; // Default Celsius
            Console.WriteLine("Hardware Initialized.");
        }
    }
}
